name: Automerge

on:
  # Try enabling auto-merge for a pull request when a draft is marked as “ready for review”, when
  # a required label is applied or when a “do not merge” label is removed, or when a pull request
  # is updated in any way (opened, synchronized, reopened, edited).
  pull_request_target:
    types:
      - opened
      - synchronized
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review

  # Try enabling auto-merge for the specified pull request or all open pull requests if none is specified.
  workflow_dispatch:
    inputs:
      pull-request:
        description: Pull Request Number
        required: false

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.TOKEN_MINT_APP_ID }}
          private_key: ${{ secrets.TOKEN_MINT_PRIVATE_KEY }}
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          merge-method: squash
          pull-request: ${{ github.event.inputs.pull-request }}
