name: Bridgette Runner Test

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/bridgette_runner_test.yaml'
      - 'bridgette/bridgette_runner/**'
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/bridgette_runner_test.yaml'
      - 'bridgette/bridgette_runner/**'

jobs:
  test:
    name: Automated tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: bridgette/bridgette_runner
    steps:
      - name: Configure auto cancellation
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Install Dart environment
        uses: dart-lang/setup-dart@v1.4
        with:
          cache: true

      - name: Install dependencies
        run: dart pub get

      - name: Analyze code
        run: dart analyze
