name: Focus Service Build & Deployment

env:
  ESSENTIAL_MAVEN_USERNAME: ${{secrets.ESSENTIAL_MAVEN_USERNAME}}
  ESSENTIAL_MAVEN_PASSWORD: ${{secrets.ESSENTIAL_MAVEN_PASSWORD}}

on:
  push:
    branches:
      - master

    tags:
      - 'focus/service/**'

    paths:
      - '.github/workflows/focus_service.yaml'
      - 'focus/service/**'
      - 'focus/postgres/**'
      - 'grpc/java/**'
      - 'grpc/proto/**'

  pull_request:
    branches:
      - master

    paths:
      - '.github/workflows/focus_service.yaml'
      - 'focus/service/**'
      - 'focus/postgres/**'
      - 'grpc/java/**'
      - 'grpc/proto/**'

  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'The services(s) to be deployed'
        required: true
        options:
          - none
          - production
          - all

jobs:
  lint:
    name: Buf
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container:
      image: bufbuild/buf:latest
    steps:
      - uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - working-directory: grpc/proto
        run: buf lint

  build-deploy:
    name: Hermetically build & deploy service
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./focus/service
    needs: [lint]
    steps:
      - uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - working-directory: focus/service
        run: ./gradlew build shadowJar

      - if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || startsWith(github.ref, 'refs/tags/focus/postgres') || inputs.target != 'none'
        run: docker build -t forus-labs/essential-focus-service .

        # This whole section is a mess. Why? It's 2022 and GitHub Actions still refuses to allow scripts to exit early.

      - if: startsWith(github.ref, 'refs/tags/focus/postgres') || inputs.target == 'production' || inputs.target == 'all'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_ESSENTIAL_PRODUCTION_CREDENTIALS }}

      - if: startsWith(github.ref, 'refs/tags/focus/postgres') || inputs.target == 'production' || inputs.target == 'all'
        uses: 'google-github-actions/setup-gcloud@v1'

      - if: startsWith(github.ref, 'refs/tags/focus/postgres') || inputs.target == 'production' || inputs.target == 'all'
        run: gcloud auth configure-docker us-docker.pkg.dev

      - if: startsWith(github.ref, 'refs/tags/focus/postgres') || inputs.target == 'production' || inputs.target == 'all'
        run: >
          docker tag 
          forus-labs/essential-focus-service 
          us-docker.pkg.dev/${{ secrets.GCP_ESSENTIAL_PRODUCTION_PROJECT_ID }}/focus-service/essential-focus-service:latest

      - if: startsWith(github.ref, 'refs/tags/focus/postgres') || inputs.target == 'production' || inputs.target == 'all'
        name: Upload Docker image to production environment
        run: docker push us-docker.pkg.dev/${{ secrets.GCP_ESSENTIAL_PRODUCTION_PROJECT_ID }}/focus-service/essential-focus-service:latest

      - if: startsWith(github.ref, 'refs/tags/focus/postgres') || inputs.target == 'production' || inputs.target == 'all'
        name: Deploy to production environment
        run: >
          gcloud run deploy focus-service
          --image us-docker.pkg.dev/${{ secrets.GCP_ESSENTIAL_PRODUCTION_PROJECT_ID }}/focus-service/essential-focus-service:latest
          --service-account ${{ secrets.GCP_ESSENTIAL_PRODUCTION_SERVICE_ACCOUNT_EMAIL }}
          --region us-west1