name: Journal Postgres Test Database Migration

on:
  push:
    branches-ignore:
      - master
    paths:
      - '.github/workflows/journal_postgres_test.yaml'
      - 'journal/postgres/**'

  workflow_dispatch: {}

env:
  FLYWAYHUB_ACCESS_TOKEN: ${{ secrets.FLYWAY_HUB_ACCESS_TOKEN }}

jobs:
  test:
    name: Test Flyway migration
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout/@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Test migrations on Flyway Hub
        uses: red-gate/flyway-hub-migration-test@v4
        with:
          projectName: essential-journal
          engine: postgres-13
          migrationDirs: journal/postgres